// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blsndloldcaeqhglfqbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsc25kbG9sZGNhZXFoZ2xmcWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTk1NDIsImV4cCI6MjA2NjMzNTU0Mn0.msiA8F95TrG4BRTOVXZ2mD-vRm7MhUkJCMXQ1jrxmCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);